// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  The dashboard read model: skills grouped by provenance. */
	getState: () => typedError<Listing, string>(__TAURI_INVOKE("get_state")),
};

/* Types */
/**  An authored skill as seen by `list`. */
export type AuthoredSkill = {
	name: string,
	/**  Whether the original directory exists in the Store. */
	present: boolean,
};

/**  A skilldock inventory grouped by provenance. */
export type Listing = {
	authored: AuthoredSkill[],
	vendored: VendoredSkill[],
};

/**  A vendored skill as seen by `list` (resolved from the lock). */
export type VendoredSkill = {
	name: string,
	repo: string,
	path: string,
	/**  The pinned commit SHA of the owning repo. */
	resolved: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

